//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.18 at 10:32:52 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/calculatorDescription", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.calculatordescription;
