//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2018.11.18 at 10:33:28 PM EST 
=======
<<<<<<< HEAD
// Generated on: 2018.11.17 at 04:53:11 PM EST 
=======
// Generated on: 2018.11.18 at 03:33:33 PM EST 
>>>>>>> e50eee3992f46da80caf64bd74ff6a9c119e104a
>>>>>>> master
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/calculatorDescription", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.calculatordescription;
